- hosts: all
  handlers:
  - name: Redhat restart httpd
    service:
      name: httpd
      state: restarted
  
  - name: Debian restart apache
    service:
      name: apache2
      state: restarted
  tasks:
  - include_tasks: "{{ ansible_os_family }}-apache.yml"

- hosts: all
  vars_files:
  - vars.yml
  tasks:
  - name: Debug
    debug:
      msg: Instance {{ ansible_os_family }} {{ text }}
